import type { Metadata } from "next";
import { Geist, Geist_Mono, Space_Grotesk } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const spaceGrotesk = Space_Grotesk({
  variable: "--font-spave-grotesk",
  weight: '700',
  subsets: ["latin",]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${spaceGrotesk.className} ${geistSans.variable} ${geistMono.variable} antialiased relative text-white bg-customShade min-h-screen`}
      >
        {/* Noisy background image */}
        <div className="fixed inset-0 bg-[url('https://framerusercontent.com/images/rR6HYXBrMmX4cRpXfXUOvpvpB0.png')] bg-repeat bg-[length:109px] opacity-[0.06] z-10" />
        {/* Semi-transparent overlay */}
        <div className="relative opacity-95 z-20">
        {children}
        </div>
      </body>
    </html>
  );
}
